### ISSUE TITLE
暗号化 -> 難読化

### ISSUE THREAD

**Issue by koba-e964** [nahco314/rain#1]
このプロジェクトで暗号化 (encryption) と呼ばれているものは難読化 (obfuscation) と呼ばれた方がわかりやすい気がします。AES 暗号化時のキーも提出に含まれていて、暗号化 (第三者が読めないように変換すること) の仕事はしていないように思えるためです。

**Comment by nahco314** [comment]
仰る通り、いわゆる暗号化とは違うと思います。
ただ、提出結果のページからは"\x00"と"\xef\xbf\xbd"の見分けが付かず、一般ユーザーからはソースコードの内容や共通鍵を復元することが恐らくできないため、難読化と呼ぶのも少し違うかなあと思っていて、何かちょうど良い言葉があればいいんですが、ひとまず暗号化と呼んでいます。

**Comment by koba-e964** [comment]
実際にページに書かれているのが `"\xef\xbf\xbd"` ばかりであって復元不可能なのを確認しました。失礼しました。
